'use client';

import { FormEvent, useState } from 'react';
import { Accessibility, ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, CheckCircle2, CircleDollarSign, Copy, Download, FileCheck2, FileText, FileX2, GitBranch, Heart, HeartOff, Landmark, LandPlot, Mail, MapPin, MapPinned, Medal, Phone, PlugZap, QrCode, ScanLine, Search, Send, ShieldCheck, Store, UploadCloud, UserPlus, UserRound, UserRoundX, UsersRound, Waves, Zap } from 'lucide-react';
import { toBn } from '@smartseba/utils';
export type PortalPageType = 'services' | 'apply' | 'trade' | 'certificate' | 'license' | 'holding' | 'citizen' | 'tax' | 'notices' | 'contact' | 'track' | 'verify';

const serviceNames = ['Citizen Certificate Application','Heir Certificate Application','Character Certificate Application','Death Certificate Application','No Re-marriage Certificate','Disability Certificate Application','Electricity Connection Certificate','Voter Area Transfer Clearance','Guardian Income Application','Freedom Fighter Application','Freedom Fighter Child Application','Same Name Application','Ethnic Minority Application','Profession Related Application','Heirship Certificate Application','Unmarried Certificate Application','Certification Application','Landless Certificate Application','National ID Card Correction','New Voter Registration Certificate','Childless Certificate Application','No Electricity Connection Application','Char Area No Electricity Application','Trade License Application'];
const serviceIcons = [
  UserRound, UsersRound, BadgeCheck, FileX2, HeartOff, Accessibility,
  Zap, MapPinned, CircleDollarSign, Medal, ShieldCheck, Copy,
  UsersRound, BriefcaseBusiness, GitBranch, Heart, FileCheck2, LandPlot,
  ScanLine, UserPlus, UserRoundX, PlugZap, Waves, Store,
];

function Header() { return <header className="navbar"><div className="container nav-inner"><a href="/" className="brand"><span className="brand-mark"><Landmark size={20} /></span><span><span className="brand-name">Digital Seba</span><span className="brand-sub">Digital Union Parishad</span></span></a><nav className="nav-links"><a href="/">Home</a><a href="/citizen-corner">Services</a><a href="/notices">Notices</a><a href="/contact-us">Contact</a></nav><a className="login-btn" href="/">Back to Homepage <ArrowRight size={14} /></a></div></header>; }
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="site-shell"><Header /><div className="page-hero"><div className="container"><a href="/" className="section-link"><ArrowLeft size={14} /> Homepage</a><h1>{title}</h1><p>{subtitle}</p></div></div><main className="form-page"><div className="container">{children}</div></main><footer className="footer"><div className="container"><div className="footer-bottom" style={{ borderTop: 0, paddingTop: 0 }}><span>&copy; 2026, Digital Seba. All Rights Reserved.</span><span>Technical Support by Digital Seba Team</span></div></div></footer></div>; }
function Field({ label, placeholder, full = false, type = 'text' }: { label: string; placeholder?: string; full?: boolean; type?: string }) { return <div className={`field ${full ? 'full' : ''}`}><label>{label}</label>{type === 'select' ? <select defaultValue=""><option value="">Select</option><option>Rajshahi</option><option>Chapainawabganj</option></select> : <input type={type} placeholder={placeholder} />}</div>; }
function Done({ title, text = 'Your information has been successfully received.' }: { title: string; text?: string }) { return <div className="form-panel" style={{ textAlign: 'center', padding: 52 }}><div className="success-icon"><CheckCircle2 size={31} /></div><h2>{title}</h2><p className="section-desc" style={{ margin: '0 auto 19px' }}>{text}</p><a className="primary-btn" href="/">Back to Homepage <ArrowRight size={15} /></a></div>; }
function SubmitForm({ children, title = 'Fill in Information', endpoint }: { children: React.ReactNode; title?: string; endpoint?: string }) {
  const [done, setDone] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [trackingNo, setTrackingNo] = useState('');

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!endpoint) { setDone(true); return; }
    setLoading(true);
    setError('');
    try {
      const form = e.currentTarget as HTMLFormElement;
      const formData = new FormData(form);
      const data = Object.fromEntries(formData.entries());
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      const result = await response.json();
      if (!response.ok) throw new Error(result.message || 'Failed to submit');
      if (result.trackingNo) setTrackingNo(result.trackingNo);
      setDone(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setLoading(false);
    }
  };

  if (done) return <Done title="Application Submitted Successfully" text={trackingNo ? `Your tracking number: ${trackingNo} — Please save this number.` : undefined} />;
  return <form className="form-panel" onSubmit={handleSubmit}><h2>{title}</h2><div className="wide-grid">{children}</div>{error && <p style={{ color: '#dc2626', fontSize: 13, marginTop: 10 }}>{error}</p>}<div className="modal-foot"><button className="primary-btn" type="submit" disabled={loading}>{loading ? 'Submitting...' : 'Submit Information'} <Send size={15} /></button></div></form>;
}
function ServicesPage() { const [query, setQuery] = useState(''); const list = serviceNames.map((name, id) => ({ name, id })).filter((item) => item.name.includes(query)); return <Shell title="Citizen Corner" subtitle="Choose the citizen service you need and apply online."><div className="service-toolbar"><div className="search-box"><Search size={16} /><input placeholder="Search by service name..." value={query} onChange={(e) => setQuery(e.target.value)} /></div><span className="service-count">{toBn(list.length)} services</span></div><div className="service-grid">{list.map(({ name, id }) => { const ServiceIcon = serviceIcons[id] ?? FileText; return <a className="service-card" href={id === 23 ? '/trade-license-apply' : `/service-apply?service=${id + 1}`} key={name}><span className="service-number service-icon" aria-label={`${name} icon`}><ServiceIcon size={16} strokeWidth={1.9} /></span><h3>{name}</h3><span className="service-apply">Apply Now <ArrowRight size={12} /></span></a>; })}</div></Shell>; }
function ApplyPage({ trade = false }: { trade?: boolean }) { return <Shell title={trade ? 'Trade License Application' : 'Service Application'} subtitle={trade ? 'Fill in your business information in both Bangla and English.' : 'Select a service and complete the application step by step.'}><SubmitForm title={trade ? 'Business Information' : 'Applicant Information'} endpoint="/api/v1/applications"><Field label="Previous Certificate No / NID No" placeholder="Enter number" /><Field label="Full Name" placeholder="Your full name" /><Field label={trade ? 'Owner/Right Holder\'s Name' : 'Father/Husband\'s Name'} placeholder="Enter name" /><Field label="Mother's Name" placeholder="Mother's Name" /><Field label="Mobile Number" placeholder="01XXXXXXXXX" /><Field label="Union" type="select" /><Field label="Ward" type="select" /><Field label={trade ? 'Business Type' : 'Holding Number'} placeholder={trade ? 'Sole / Joint / Others' : 'Holding Number'} /><Field label={trade ? 'Business Address' : 'Current Address'} placeholder="Village, Post Office, Ward" full /><Field label={trade ? 'Business Start Date' : 'Birth Registration/NID Copy'} type={trade ? 'date' : 'file'} /><Field label={trade ? 'Business Capital' : 'Holding Tax Receipt'} placeholder={trade ? 'Amount in Taka' : 'Upload file'} /></SubmitForm></Shell>; }
function DownloadPage({ license = false }: { license?: boolean }) { const [found, setFound] = useState(false); return <Shell title={license ? 'License Download / Verification' : 'Certificate Download / Verification'} subtitle="Search your document by number and verify authenticity."><div className="form-panel"><div className="step-row"><span className="step-item active"><b className="step-num">1</b>Enter Number</span><span className="step-item"><b className="step-num">2</b>Results</span><span className="step-item"><b className="step-num">3</b>Download</span></div><div className="field"><label>{license ? 'License Number' : 'Certificate Number'}</label><input placeholder={license ? 'DL-UN01-2026-0042' : 'DS-UN01-CIT-2026-0042'} /></div><div className="modal-foot"><button className="primary-btn" onClick={() => setFound(true)}>Verify <Search size={15} /></button></div>{found && <div className="notice-card" style={{ marginTop: 22, display: 'flex', alignItems: 'center', gap: 14 }}><div className="success-icon" style={{ margin: 0, width: 48, height: 48 }}><BadgeCheck size={24} /></div><div style={{ flex: 1 }}><h3 style={{ margin: 0 }}>VALID &middot; Information Found</h3><p>Name: Md. Rafiqul Islam &middot; Union 01 &middot; Issue: 18 September 2026</p></div><button className="icon-btn" aria-label="Download"><Download size={17} /></button></div>}</div></Shell>; }
function HoldingPage({ citizen = false }: { citizen?: boolean }) { return <Shell title={citizen ? 'Citizen Registration' : 'Holding Registration'} subtitle="Fill in the form with correct information. Verification will be done from the office if needed."><SubmitForm title={citizen ? 'Citizen Information' : 'Head of Household Information'} endpoint="/api/v1/applications"><Field label="Holding Number" placeholder="Holding Number" /><Field label="Name" placeholder="Full Name" /><Field label="Father/Husband's Name" placeholder="Enter name" /><Field label="Mother's Name" placeholder="Enter name" /><Field label="Mobile Number" placeholder="01XXXXXXXXX" /><Field label="Religion" type="select" /><Field label="Gender" type="select" /><Field label="Occupation" placeholder="Enter occupation" /><Field label="District" type="select" /><Field label="Upazila" type="select" /><Field label="Union" type="select" /><Field label="Ward" type="select" /><Field label="Village / Ward" placeholder="Village name" /><Field label="Photo / NID Copy" type="file" /><Field label="Additional Information" placeholder="Write if needed" full /></SubmitForm></Shell>; }
function TaxPage() { const [checked, setChecked] = useState(false); return <Shell title="Tax Payment / Verification" subtitle="Check arrears by holding number and pay online."><div className="form-panel"><h2>Search Holding</h2><div className="wide-grid"><Field label="District" type="select" /><Field label="Upazila" type="select" /><Field label="Union" type="select" /><Field label="Ward" type="select" /><Field label="Holding Number" placeholder="Holding Number" /><Field label="Fiscal Year" type="select" /></div><div className="modal-foot"><button className="primary-btn" onClick={() => setChecked(true)}>View Arrears <Search size={15} /></button></div>{checked && <div className="notice-card" style={{ marginTop: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3>Holding 123/45 &middot; Total Arrears</h3><strong style={{ color: '#087152' }}>$ 1,850</strong></div><p>Fiscal Year 2025&ndash;2026 &middot; Annual Value $ 25,000 &middot; Paid $ 650</p><button className="primary-btn">Pay Online <ArrowRight size={15} /></button></div>}</div></Shell>; }
function NoticesPage() { return <Shell title="Notice Board" subtitle="Latest announcements and important information from Union Parishad."><div className="notices-list">{['New service added to Digital Seba platform', '2025-2026 Fiscal Year Holding Tax Payment Notice', 'Office schedule and citizen service information'].map((x, i) => <article className="notice-card" key={x}><span className="date">18 September 2026 &middot; {i === 0 ? 'All Unions' : 'Union 01'}</span><h3>{x}</h3><p>This notice is published for the convenience of citizens. For detailed information, contact the office or use the Digital Seba platform.</p></article>)}</div></Shell>; }
function ContactPage() { return <Shell title="Contact" subtitle="Let us know your feedback, questions, or suggestions."><div className="download-grid"><div className="form-panel"><h2>Send Message</h2><SubmitForm endpoint="/api/v1/public/contact"><Field label="Your Name" placeholder="Enter name" /><Field label="Mobile Number" placeholder="01XXXXXXXXX" /><Field label="Message Subject" placeholder="Enter subject" /><Field label="Your Message" placeholder="Enter details" full /></SubmitForm></div><div className="form-panel"><h2>Contact Address</h2><div className="contact-line"><Phone size={16} /> +880 1788812345</div><div className="contact-line"><Mail size={16} /> hello@digitalseba.org</div><div className="contact-line"><MapPin size={16} /> Digital Seba Parishad, Rajshahi</div><div style={{ marginTop: 25, height: 180, borderRadius: 15, background: 'linear-gradient(135deg,#e9f5eb,#d8ebde)', display: 'grid', placeItems: 'center', color: '#55906d' }}><MapPin size={30} /></div></div></div></Shell>; }
function TrackPage({ trackingNo = 'DS-UN01-2026-784152' }: { trackingNo?: string }) { return <Shell title="Application Tracking" subtitle={`Tracking number: ${trackingNo}`}><div className="form-panel"><div className="timeline" style={{ color: '#315' }}><div className="timeline-step"><div className="timeline-dot done"><BadgeCheck size={15} /></div><strong style={{ color: '#315748' }}>Submitted</strong><span>18 September 2026</span></div><div className="timeline-step"><div className="timeline-dot done"><BadgeCheck size={15} /></div><strong style={{ color: '#315748' }}>Initial Verification</strong><span>18 September 2026</span></div><div className="timeline-step"><div className="timeline-dot"><ShieldCheck size={15} /></div><strong style={{ color: '#315748' }}>Approval</strong><span>In Progress</span></div><div className="timeline-step"><div className="timeline-dot"><Download size={15} /></div><strong style={{ color: '#315748' }}>Delivery</strong><span>Next Step</span></div></div><div className="notice-card" style={{ marginTop: 35 }}><h3>Citizen Certificate Application</h3><p>Applicant: Md. Rafiqul Islam &middot; Union: Union 01 &middot; Current Status: Awaiting Approval</p></div></div></Shell>; }
function VerifyPage({ code = 'DS-UN01-CIT-2026-0042' }: { code?: string }) { return <Shell title="Document Verification" subtitle="Verify the authenticity of issued documents using QR code or number."><div className="form-panel" style={{ textAlign: 'center' }}><div className="success-icon"><BadgeCheck size={32} /></div><h2 style={{ color: '#087152' }}>VALID &middot; Document is Authentic</h2><p className="section-desc" style={{ margin: '0 auto 22px' }}>Certificate Number: {code}</p><div className="notice-card" style={{ textAlign: 'left', maxWidth: 450, margin: '0 auto' }}><h3>Citizen Certificate</h3><p>Name: Md. Rafiqul Islam<br />Union: Union 01<br />Issue Date: 18 September 2026</p></div><button className="secondary-btn" style={{ marginTop: 22 }}><QrCode size={16} /> Scan QR Code</button></div></Shell>; }

export function PortalPage({ type, value }: { type: PortalPageType; value?: string }) { switch (type) { case 'services': return <ServicesPage />; case 'apply': return <ApplyPage />; case 'trade': return <ApplyPage trade />; case 'certificate': return <DownloadPage />; case 'license': return <DownloadPage license />; case 'holding': return <HoldingPage />; case 'citizen': return <HoldingPage citizen />; case 'tax': return <TaxPage />; case 'notices': return <NoticesPage />; case 'contact': return <ContactPage />; case 'track': return <TrackPage trackingNo={value} />; case 'verify': return <VerifyPage code={value} />; default: return <ServicesPage />; } }
